In [1]:
pip install kafka-python

Collecting kafka-python
  Downloading kafka_python-2.0.2-py2.py3-none-any.whl.metadata (7.8 kB)
Downloading kafka_python-2.0.2-py2.py3-none-any.whl (246 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.5/246.5 kB 15.4 MB/s eta 0:00:00
Installing collected packages: kafka-python
Successfully installed kafka-python-2.0.2

In [2]:
import pandas as pd
from kafka import KafkaProducer
from time import sleep
from json import dumps
import json

In [18]:
producer = KafkaProducer(bootstrap_servers=['13.60.84.55:9092'], #change ip here
                         value_serializer=lambda x:
                         dumps(x).encode('utf-8'))

In [27]:
producer.send('demo_test', value={'Name':'Vaibhav'})

In [4]:
from google.colab import files

In [5]:
import pandas as pd

file_path = '/content/drive/My Drive/indexProcessed.csv'  # Replace with the correct path
df = pd.read_csv(file_path)

In [6]:
df.head()

,Index,Date,Open,High,Low,Close,Adj Close,Volume,CloseUSD
0,HSI,1986-12-31,2568.300049,2568.300049,2568.300049,2568.300049,2568.300049,0.0,333.879006
1,HSI,1987-01-02,2540.100098,2540.100098,2540.100098,2540.100098,2540.100098,0.0,330.213013
2,HSI,1987-01-05,2552.399902,2552.399902,2552.399902,2552.399902,2552.399902,0.0,331.811987
3,HSI,1987-01-06,2583.899902,2583.899902,2583.899902,2583.899902,2583.899902,0.0,335.906987
4,HSI,1987-01-07,2607.100098,2607.100098,2607.100098,2607.100098,2607.100098,0.0,338.923013

In [7]:
df.sample(1)

,Index,Date,Open,High,Low,Close,Adj Close,Volume,CloseUSD
78768,NSEI,2016-10-21,8708.599609,8709.099609,8652.049805,8693.049805,8693.049805,157300.0,86.930498

In [32]:
while True:
    dict_stock = df.sample(1).to_dict(orient="records")[0]
    producer.send('demo_test', value=dict_stock)
    sleep(1)

KeyboardInterrupt:

In [31]:
producer.flush() #clear data from kafka server